version: "3"

services:
  discovery-service:
    container_name: "discovery-service"
    build:
      context: ./discovery-server
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    volumes:
      - C:\dev\dockerize:/usr/local/bin/dockerize
    networks:
      - yul-ecommerce


  config-service:
    container_name: "config-service"
    build:
      context: ./config-server
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - C:\dev\config:/config
      - C:\dev\dockerize:/usr/local/bin/dockerize
    networks:
      - yul-ecommerce
    environment:
      - EUREKA_CLIENT_SERVICE-URL_DEFAULT-ZONE=http://discovery-service:8761/eureka
      - ENCRYPT_KEY-STORE_LOCATION=file:/apiEncryptionKey.jks
    command: ["dockerize", "-wait", "tcp://mariadb-service:3306", "-wait", "http://discovery-service:8761", "-timeout", "20s", "java","-jar","ConfigService.jar"]

  gateway-service:
    container_name: "gateway-service"
    build:
      context: ./gateway-service
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - C:\dev\dockerize:/usr/local/bin/dockerize
    networks:
      - yul-ecommerce
    environment:
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8888
      - EUREKA_CLIENT_SERVICE-URL_DEFAULT-ZONE=http://discovery-service:8761/eureka
    command: ["dockerize", "-wait", "http://config-service:8888", "-wait", "http://discovery-service:8761", "-timeout", "20s", "java","-jar","GatewayService.jar"]

networks:
  yul-ecommerce:
    external: true