version: "3"

services:
  compose_rabbitmq:
    container_name: "compose_rabbitmq"
    image: rabbitmq:management
    ports:
      - "15672:15672"
      - "5672:5672"
      - "15671:15671"
      - "5671:5671"
      - "4369:4369"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  compose_redis:
    container_name: "compose_redis"
    image: redis:7.0.0
    ports:
      - "6379:6379"

  mariadb-service:
    container_name: "mariadb"
    image: mariadb:latest
    ports:
      - "13306:3306"
    volumes:
      - C:\dev\sideprojectDB\auth:/var/lib/mysql
    networks:
      - yul-ecommerce
    environment:
      - MYSQL_ROOT_PASSWORD=yula1234
      - TZ=Asia/Seoul

  h2db-service:
    container_name: "h2"
    image: oscarfonts/h2:latest
    ports:
      - "1521:1521"
      - "8011:81"
    volumes:
      - C:\dev\sideprojectDB\board:/opt/h2-data
    networks:
      - yul-ecommerce
    environment:
      - H2_OPTIONS=-ifNotExists

networks:
  yul-ecommerce:
    external: true

