server:
  port: 8888


spring:
  cloud:
    config:
      server:
        native:
          searchLocations: "{cipher}9df5b4d3eb11706853e7371d462b491f3390fe7ea4d207eec629dbbeab8a0fcf"
        encrypt:
          enabled: false

  application:
    name: config-server

  profiles:
    active: native

eureka:

  instance:
    instance-id: ${spring.cloud.client.ip-address}:${random.value}

  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    shutdown:
      enabled: true
encrypt:
  key: key-brian
